FROM alpine:latest
MAINTAINER "Panhao Wu" <ekinghao@gmail.com>

RUN apk add --update nginx && rm -rf /var/cache/apk/*
# RUN mkdir -p /tmp/nginx/client-body

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY www /www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]