#
# Dockerfile for Ubuntu in Workspace
#
# https://github.com/dockerfile/nginx
#

# Pull base image.
FROM ubuntu:latest

# Install Nginx.
RUN apt-get update && \
  apt-get install -y curl && \
  apt-get install -y zsh tmux
#  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

CMD ["/bin/bash"]
